# Generated by Django 3.1.2 on 2020-10-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_gallery', '0002_photos_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'ordering': ['name']},
        ),
    ]
