# Generated by Django 3.1.2 on 2020-10-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_gallery', '0004_auto_20201013_0752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='image',
            new_name='photo_image',
        ),
    ]
