# Generated by Django 3.1.2 on 2020-10-14 07:15

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_gallery', '0005_auto_20201013_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
