# Generated by Django 3.1.2 on 2020-10-14 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_gallery', '0006_photos_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='photo_image',
        ),
    ]
